"""create ingestion_jobs

Revision ID: 388ab7a6550d
Revises:
Create Date: 2026-08-27 07:16:00.436120+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "388ab7a6550d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("group_id", sa.String(length=256), nullable=False),
        sa.Column("source_id", sa.String(length=512), nullable=False),
        sa.Column("dedup_uuid", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="8", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_visible_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('pending','inflight','done','dead')", name="ck_jobs_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_uuid", name="uq_jobs_dedup"),
    )
    op.create_index(
        "ix_jobs_claimable",
        "ingestion_jobs",
        ["group_id", "next_visible_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_jobs_claimable",
        table_name="ingestion_jobs",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("ingestion_jobs")
    # ### end Alembic commands ###
