"""llm_usage

Revision ID: dc5ccddfa2ca
Revises: e06a069990aa
Create Date: 2026-08-27 10:06:10.591547+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc5ccddfa2ca"
down_revision: str | None = "e06a069990aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("request_kind", sa.String(length=16), nullable=False),
        sa.Column("group_id", sa.String(length=256), nullable=True),
        sa.Column("ref", sa.String(length=512), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Float(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint("operation IN ('llm','embedding')", name="ck_llm_usage_operation"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_usage_group_time", "llm_usage", ["group_id", "occurred_at"], unique=False
    )
    op.create_index("ix_llm_usage_ref", "llm_usage", ["ref"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_usage_ref", table_name="llm_usage")
    op.drop_index("ix_llm_usage_group_time", table_name="llm_usage")
    op.drop_table("llm_usage")
    # ### end Alembic commands ###
