"""published_episodes authority

Revision ID: e06a069990aa
Revises: 549e6556e266
Create Date: 2026-08-27 08:53:16.043179+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e06a069990aa"
down_revision: str | None = "549e6556e266"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "published_episodes",
        sa.Column("authority", sa.Float(), server_default="0.5", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("published_episodes", "authority")
    # ### end Alembic commands ###
